// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdDmDjRxJPlr1kKymdQXhYvLtEnqwe-DE',
    appId: '1:239990148881:web:01d8ec1d971d5e0d5206b0',
    messagingSenderId: '239990148881',
    projectId: 'zoom-clone-cde23',
    authDomain: 'zoom-clone-cde23.firebaseapp.com',
    storageBucket: 'zoom-clone-cde23.appspot.com',
    measurementId: 'G-WHHKMD34GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEmDf5_K65GYmqVoedNR-aI0fquFdjN-c',
    appId: '1:239990148881:android:8f65655f36bd60995206b0',
    messagingSenderId: '239990148881',
    projectId: 'zoom-clone-cde23',
    storageBucket: 'zoom-clone-cde23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb_6eZ3VbyvYBwiIcRwyKgwDPTWfvD_KQ',
    appId: '1:239990148881:ios:246d0c561bce31295206b0',
    messagingSenderId: '239990148881',
    projectId: 'zoom-clone-cde23',
    storageBucket: 'zoom-clone-cde23.appspot.com',
    iosClientId: '239990148881-kun1p773e11fo32vqtco10vq0ebbqps8.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb_6eZ3VbyvYBwiIcRwyKgwDPTWfvD_KQ',
    appId: '1:239990148881:ios:246d0c561bce31295206b0',
    messagingSenderId: '239990148881',
    projectId: 'zoom-clone-cde23',
    storageBucket: 'zoom-clone-cde23.appspot.com',
    iosClientId: '239990148881-kun1p773e11fo32vqtco10vq0ebbqps8.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
